### PR TITLE
Add feature to read excel files from local file / remote url

### PR DESCRIPTION
**Pull request by adzo261**
Refers to issue #27.

Points to note:
1.  Using npm package [xlsx](https://www.npmjs.com/package/xlsx).
2.  Assuming the following format: The first non-empty row represents column array and next rows represent data until the last non-empty row in the Excel file. Refer the sample file (`SampleData.xlsx`) to get clarity.
3.  Added tests for the same.
4. Created a new folder `/tests/samples` to store sample data files being used for testing.

If you think we can do better for point 2, let's discuss it. It may become surprisingly complex if we don't make the assumption.

### CODE REVIEW

**Comment by JhennerTigreros** [comment]
The code is ok, but I think is useful to use snake case to define variables or functions, this to have consistency of the rest of the base code.

For the second assumption, I think you can pass a parameter to the `read_excel` like `index_col` in pandas, and with this you select what row is the columns name, if the user don't send `index_col` param you can set this to 1 for default

**Comment by adzo261** [comment]
Cool. I will refactor the code to the snake case and will add optional param to identify column row.

**Comment by adzo261** [comment]
I have added support to optionally specify the index from which header/column names' start, and also the index from which data/body/content starts. Please have a look. Thanks.

**Comment by steveoni** [comment]
Nice work @adzo261 . 

I just want to ask. if the user must specified the excel file base on the current working directory or absolute directory (e.g ~/directory/example_folder/SampleData.xlsx')

**Comment by adzo261** [comment]
> I just want to ask. if the user must specified the excel file base on the current working directory or absolute directory (e.g ~/directory/example_folder/SampleData.xlsx')

I think both should work. For relative paths, one can use `path.join` from `path` npm package. And for absolute paths, one can specify directly. Note that the function used by `XLSX` internally is same as `readFile` which we use as usual.

**Comment by adzo261** [comment]
> Nice work @adzo261 .

Thanks for merging. 
Nice work by you guys as well. Great going so far. :1st_place_medal: 
Had a great time working on it!

**Comment by risenW** [comment]
> > Nice work @adzo261 .
> 
> Thanks for merging.
> Nice work by you guys as well. Great going so far. 🥇
> Had a great time working on it!

Thanks @adzo261 and well done!

**Comment by george-assan** [comment]
Seems this functionality currently accepts array indices for the sheet param not the name

in documentation  it says for danfo.readExcel(source, options) , options accepts sheet param like so:
{
sheet : string, (Optional) Name of the sheet which u want to parse. Default will be the first sheet.
}

however,  in the readExcel code **workbook.SheetNames**   in line below returns an array of sheet names i.e. ['sheet 1','sheet 2' ..]  which means the sheet param has to be an int representing the index of the sheet 

const worksheet = workbook.Sheets[workbook.SheetNames[sheet]];

**Pull request merged**
